# Generated by Django 5.1.2 on 2024-10-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_drivingdata_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingdata',
            name='user',
        ),
    ]
