# Generated by Django 5.1.2 on 2024-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_remove_drivingdata_user_number_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingdata',
            name='overall_average_electric_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='overall_average_fuel_consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
