# Generated by Django 5.1.2 on 2024-10-15 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_drivingdata_overall_average_electric_consumption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingdata',
            name='number_of_hard_brakes_per_1000km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='number_of_rash_drives_per_1000km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='overall_average_speed_in_kmph',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='overall_average_travel_time_in_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='total_distance_traveled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingdata',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
